workspace = { members = ["examples/account", "examples/auth_verify", "examples/idp"] }
[package]
name = "oidc-rp"
description = "Implements OIDC Relying Party methods"
version = "0.0.1"
edition = "2021"
authors = ["Leonard Marschke <leo@mixxplorer.de>"]
readme = "Readme.md"
repository = "https://rechenknecht.net/mixxplorer/libraries/oidc-rp"
license = "MIT OR Apache-2.0"
keywords = ["oidc", "oauth", "authentication"]
categories = ["authentication"]

[badges]
maintenance = { status = "experimental" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "~0.4"
serde = { version = "1", features = ["std", "derive"] }
serde_json = "1"
url = { version = "2.5", features = ["serde"] }
thiserror = "1.0"
reqwest = { version = "0.12", features = ["http2", "rustls-tls-native-roots", "brotli", "json"] }
# openidconnect = { git = "https://github.com/ramosbugs/openidconnect-rs.git", branch = "main", default-features = false, features = ["timing-resistant-secret-traits", "reqwest-blocking"] }
openidconnect = { path = "../openidconnect-rs", default-features = false, features = ["timing-resistant-secret-traits", "reqwest-blocking", "jwt-access-token"] }
chrono = "0.4"
tokio = { version = "1.37.0", features = ["sync", "macros"] }
tokio-util = { version = "0.7" }
