workspace = { members = ["examples/account", "examples/auth_verify", "examples/idp", "examples/leptos-axum-oidc"] }
[package]
name = "oidc-rp"
description = "Implements OIDC Relying Party methods"
version = "0.0.1"
edition = "2021"
authors = ["Leonard Marschke <leo@mixxplorer.de>"]
readme = "Readme.md"
repository = "https://rechenknecht.net/mixxplorer/libraries/oidc-rp"
license = "MIT OR Apache-2.0"
keywords = ["oidc", "oauth", "authentication"]
categories = ["authentication"]

[badges]
maintenance = { status = "experimental" }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
wasm = ["dep:web-sys"]
integrations = []
leptos = ["integrations", "wasm", "dep:leptos", "dep:leptos_router"]
js = ["integrations", "wasm"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "~0.4"
serde = { version = "1", features = ["std", "derive"] }
serde_json = "1"
url = { version = "2.5", features = ["serde"] }
thiserror = "1.0"
reqwest = { version = "0.12", features = ["http2", "rustls-tls-native-roots", "brotli", "json"] }
# openidconnect = { git = "https://github.com/ramosbugs/openidconnect-rs.git", branch = "main", default-features = false, features = ["timing-resistant-secret-traits", "reqwest-blocking"] }
openidconnect = { git = "https://github.com/mixxplorer/openidconnect-rs.git", branch = "feature/jwt-access-tokens", default-features = false, features = ["timing-resistant-secret-traits", "reqwest-blocking", "jwt-access-token"] }
# openidconnect = { path = "../openidconnect-rs", default-features = false, features = ["timing-resistant-secret-traits", "reqwest-blocking", "jwt-access-token"] }
chrono = "0.4"
tokio = { version = "1.37.0", features = ["sync", "macros"] }
tokio-util = { version = "0.7" }
futures = "0.3.30"

leptos = { version = "0.6", optional = true }
leptos_router = { version = "0.6", optional = true }
web-sys = { version = "0.3.69", features = ["Window", "Location", "Storage"], optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.42"
web-sys = "0.3.69"
gloo-timers = { version = "0.3.0", features = ["futures"] }
wasm-bindgen = "0.2.92"
console_error_panic_hook = "0.1.7"


[target.'cfg(target_arch = "wasm32")'.profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

# For leptus-axum-oidc example
[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"


[profile.release]
lto = true
panic = "abort"
opt-level = 'z'
